version: 2
jobs:
   build:
     docker:
       - image: circleci/php:latest
     steps:
       - checkout
       - run: echo "hello world"
notify:
   webhooks:
     - url: https://requestb.in/10inzf91
