version: 2
jobs:
   build:
     docker:
       - image: circleci/php:latest
     environment:
      TZ: "/usr/share/zoneinfo/America/New_York"
     steps:
       - checkout
       - run: echo "hello world"
       - run: curl -X POST -d "fizz=buzz" https://requestb.in/10inzf91
       - run:
          command: |
            echo "Running test"
            mkdir -p /tmp/test-results
       
notify:
   webhooks:
     - url: https://requestb.in/10inzf91
