version: 2
jobs:
  build:
    machine:
      image: circleci/classic:latest
    working_directory: ~/repo
    steps:
      - checkout
      - run: npm install -g node@8.9.0
      - run: node --version && npm --version && npm install
      - run:
          name: Lint
          command: npm run lint
